# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import calculator_pb2 as calculator__pb2


class CalculatorServiceStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.Calculate = channel.stream_stream(
        '/CalculatorService/Calculate',
        request_serializer=calculator__pb2.OperationRequest.SerializeToString,
        response_deserializer=calculator__pb2.OperationResponse.FromString,
        )


class CalculatorServiceServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def Calculate(self, request_iterator, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_CalculatorServiceServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'Calculate': grpc.stream_stream_rpc_method_handler(
          servicer.Calculate,
          request_deserializer=calculator__pb2.OperationRequest.FromString,
          response_serializer=calculator__pb2.OperationResponse.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'CalculatorService', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
