# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: greeting.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='greeting.proto',
  package='',
  syntax='proto3',
  serialized_options=_b('\252\002\tGenerated'),
  serialized_pb=_b('\n\x0egreeting.proto\"7\n\x0fGreetingRequest\x12\x0f\n\x07message\x18\x01 \x01(\t\x12\x13\n\x0bsender_name\x18\x02 \x01(\t\"#\n\x10GreetingResponse\x12\x0f\n\x07message\x18\x01 \x01(\t2?\n\x0fGreetingService\x12,\n\x05Greet\x12\x10.GreetingRequest\x1a\x11.GreetingResponseB\x0c\xaa\x02\tGeneratedb\x06proto3')
)




_GREETINGREQUEST = _descriptor.Descriptor(
  name='GreetingRequest',
  full_name='GreetingRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='message', full_name='GreetingRequest.message', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='sender_name', full_name='GreetingRequest.sender_name', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=18,
  serialized_end=73,
)


_GREETINGRESPONSE = _descriptor.Descriptor(
  name='GreetingResponse',
  full_name='GreetingResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='message', full_name='GreetingResponse.message', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=75,
  serialized_end=110,
)

DESCRIPTOR.message_types_by_name['GreetingRequest'] = _GREETINGREQUEST
DESCRIPTOR.message_types_by_name['GreetingResponse'] = _GREETINGRESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

GreetingRequest = _reflection.GeneratedProtocolMessageType('GreetingRequest', (_message.Message,), dict(
  DESCRIPTOR = _GREETINGREQUEST,
  __module__ = 'greeting_pb2'
  # @@protoc_insertion_point(class_scope:GreetingRequest)
  ))
_sym_db.RegisterMessage(GreetingRequest)

GreetingResponse = _reflection.GeneratedProtocolMessageType('GreetingResponse', (_message.Message,), dict(
  DESCRIPTOR = _GREETINGRESPONSE,
  __module__ = 'greeting_pb2'
  # @@protoc_insertion_point(class_scope:GreetingResponse)
  ))
_sym_db.RegisterMessage(GreetingResponse)


DESCRIPTOR._options = None

_GREETINGSERVICE = _descriptor.ServiceDescriptor(
  name='GreetingService',
  full_name='GreetingService',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=112,
  serialized_end=175,
  methods=[
  _descriptor.MethodDescriptor(
    name='Greet',
    full_name='GreetingService.Greet',
    index=0,
    containing_service=None,
    input_type=_GREETINGREQUEST,
    output_type=_GREETINGRESPONSE,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_GREETINGSERVICE)

DESCRIPTOR.services_by_name['GreetingService'] = _GREETINGSERVICE

# @@protoc_insertion_point(module_scope)
