# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import greeting_pb2 as greeting__pb2


class GreetingServiceStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.Greet = channel.unary_unary(
        '/GreetingService/Greet',
        request_serializer=greeting__pb2.GreetingRequest.SerializeToString,
        response_deserializer=greeting__pb2.GreetingResponse.FromString,
        )


class GreetingServiceServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def Greet(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_GreetingServiceServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'Greet': grpc.unary_unary_rpc_method_handler(
          servicer.Greet,
          request_deserializer=greeting__pb2.GreetingRequest.FromString,
          response_serializer=greeting__pb2.GreetingResponse.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'GreetingService', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
